spring:
  application:
    name: security-demo
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "407984416427-f0n3lf2v2pjld8nu4970hmhrgnbbp9ll.apps.googleusercontent.com"
            client-secret: "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"

logging:
  level:
    org.springframework.security: TRACE

